services:
  zako-issuetracker:
    image: zako-issuetracker
    build:
      context: .
      dockerfile: zako-issuetracker/Dockerfile
    environment:
      DISCORD_TOKEN:
      SQLITE_FILE: /data/zako.sqlite
      ADMIN_IDS:
      EMBED_PAGE_SIZE: 5
    volumes:
      - ./data:/data:rw
